/**
 * Business context: defines the plain-data boundary between the development
 * simulator UI and its Worker. Routing graphs and binary cells remain inside
 * the Worker while reproducible GPX scenarios and aggregate metrics cross it.
 */
import type { Coordinate } from 'ol/coordinate.js';

/** One deterministic simulator scenario prepared from an uploaded GPX segment. */
export interface RoutingSimulatorScenario {
  /** Stable row identifier generated by the UI. */
  id: string;
  /** Original uploaded GPX filename. */
  sourceFilename: string;
  /** GPX route and segment label. */
  sourceName: string;
  /** Sampling description such as `regular 750 m`. */
  scenarioLabel: string;
  /** Length of the original GPX segment in metres. */
  sourceDistanceMetres: number;
  /** Synthetic click coordinates in EPSG:2056. */
  waypoints: Coordinate[];
}

/** Binary corridor policies compared by the simulator. */
export type RoutingSimulatorPolicy = 'legacy' | 'certified';

/** Per-section output retained for route-quality comparisons. */
export interface RoutingSimulatorSectionResult {
  /** Zero-based section index after the first snapped waypoint. */
  sectionIndex: number;
  /** Whether network routing found a path rather than using a straight fallback. */
  routed: boolean;
  /** Number of coordinates in the routed path, or two for a straight fallback. */
  coordinateCount: number;
  /** Horizontal length of the displayed section in metres. */
  distanceMetres: number;
  /** Deterministic hash of centimetre-quantized section coordinates. */
  geometryHash: string;
}

/** Aggregate measurements for one policy and one scenario. */
export interface RoutingSimulatorPolicyResult {
  /** Corridor policy used by the engine. */
  policy: RoutingSimulatorPolicy;
  /** Number of synthetic clicks including the first point. */
  waypointCount: number;
  /** Number of route sections after the first click. */
  sectionCount: number;
  /** Sections found on the routing graph. */
  routedSectionCount: number;
  /** Sections that fell back to a direct line. */
  straightSectionCount: number;
  /** Unique binary cells requested after engine-level caching. */
  uniqueCellCount: number;
  /** Total cell-load calls, including any reload after raw-cache eviction. */
  cellLoadCount: number;
  /** Intrinsic Brotli bytes for all logical cell loads when integrity metadata exists. */
  compressedBytes: number | null;
  /** Decoded binary bytes for all logical cell loads. */
  decodedBytes: number;
  /** Exact corridor graphs assembled during the session. */
  graphBuildCount: number;
  /** Exact corridor graph-cache hits during the session. */
  graphReuseCount: number;
  /** Sum of conservative graph sizes at construction time. */
  graphBuiltBytes: number;
  /** Number of metric-envelope decisions emitted by the certified policy. */
  metricAttemptCount: number;
  /** Number of radius-based route attempts executed by this policy. */
  legacyAttemptCount: number;
  /** Certified-policy outcomes grouped by stable diagnostic code. */
  metricOutcomeCounts: Record<string, number>;
  /** Total displayed route length across all sections. */
  routedDistanceMetres: number;
  /** Wall-clock duration; useful locally but affected by the browser HTTP cache. */
  elapsedMilliseconds: number;
  /** Detailed route sections used to compare policy outputs. */
  sections: RoutingSimulatorSectionResult[];
}

/** Cross-policy quality comparison for one scenario. */
export interface RoutingSimulatorComparison {
  /** Sections whose centimetre-quantized geometry is exactly identical. */
  exactSectionCount: number;
  /** Sections with different geometry but the same routed/fallback outcome. */
  differentGeometrySectionCount: number;
  /** Sections where only one policy found a network path. */
  routingOutcomeMismatchCount: number;
  /** Largest absolute route-length difference across sections. */
  maximumSectionDistanceDifferenceMetres: number;
  /** Largest sampled symmetric deviation between differing route geometries. */
  maximumSampledDeviationMetres: number;
}

/** Complete row returned for one GPX sampling scenario. */
export interface RoutingSimulatorScenarioResult {
  /** Input scenario metadata without the potentially large waypoint array. */
  scenario: Omit<RoutingSimulatorScenario, 'waypoints'> & {
    waypointCount: number;
  };
  /** Release-1.2 radius-1/radius-2 behaviour. */
  legacy: RoutingSimulatorPolicyResult;
  /** Current certified metric-envelope behaviour. */
  certified: RoutingSimulatorPolicyResult;
  /** Route-quality comparison between both outputs. */
  comparison: RoutingSimulatorComparison;
}

/** Starts a fresh batch with independent engine sessions per scenario. */
export interface RoutingSimulatorStartRequest {
  /** Request discriminator handled by the Worker. */
  type: 'start';
  /** Normalized public root containing manifest, integrity, and binary cells. */
  routingDataBaseUrl: string;
  /** Prepared GPX scenarios executed sequentially. */
  scenarios: RoutingSimulatorScenario[];
}

/** Cancels the active batch and discards its engines. */
export interface RoutingSimulatorCancelRequest {
  /** Request discriminator handled by the Worker. */
  type: 'cancel';
}

/** Every message accepted by the simulator Worker. */
export type RoutingSimulatorWorkerRequest =
  | RoutingSimulatorStartRequest
  | RoutingSimulatorCancelRequest;

/** Worker notification emitted after each completed scenario. */
export interface RoutingSimulatorProgressResponse {
  /** Response discriminator. */
  type: 'progress';
  /** Number of scenarios completed so far. */
  completed: number;
  /** Total scenarios in the active batch. */
  total: number;
  /** Newly completed result row. */
  result: RoutingSimulatorScenarioResult;
}

/** Worker notification emitted after the complete batch. */
export interface RoutingSimulatorCompleteResponse {
  /** Response discriminator. */
  type: 'complete';
  /** Human-readable metadata warning, or `null`. */
  warning: string | null;
}

/** Worker notification emitted when the active batch fails. */
export interface RoutingSimulatorErrorResponse {
  /** Response discriminator. */
  type: 'error';
  /** Error name retained for diagnosis. */
  name: string;
  /** Actionable failure text displayed by the simulator page. */
  message: string;
  /** Optional development stack. */
  stack?: string;
}

/** Worker notification emitted after explicit cancellation. */
export interface RoutingSimulatorCancelledResponse {
  /** Response discriminator. */
  type: 'cancelled';
}

/** Every response emitted by the simulator Worker. */
export type RoutingSimulatorWorkerResponse =
  | RoutingSimulatorProgressResponse
  | RoutingSimulatorCompleteResponse
  | RoutingSimulatorErrorResponse
  | RoutingSimulatorCancelledResponse;
